version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.4
    commands:
      - echo Installing dependencies...
      - cd src
      - composer install
  build:
    commands:
      - echo Building Laravel application...
      - cp .env.example .env
      - php artisan key:generate
      - php artisan cache:clear
      - php artisan config:cache
      - php artisan route:cache
      - php artisan view:cache
artifacts:
  files:
    - '**/*'
  base-directory: base_dir
  name: pm_app
  discard-paths: no