version: 0.2

env:
  variables:
    ARTIFACTS_LOCATION: "/codebuild/output/my-app.zip"

phases:
  install:
    runtime-versions:
      php: 7.4
    commands:
      - echo Installing dependencies...
      - cd src
      - composer install
  build:
    commands:
      - echo Building Laravel application...
      - cp .env.example .env
      - php artisan key:generate
      - php artisan cache:clear
      - php artisan config:cache
      - php artisan route:cache
      - php artisan view:cache
  post_build:
    commands:
      - echo Adding additional files to artifact
      - zip -r $ARTIFACTS_LOCATION .