version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.4
    commands:
      - yum -y install httpd
      - echo Installing dependencies...
      - cd /var/www/html
      - composer install
  build:
    commands:
      - echo Building Laravel application...
      - cd /var/www/html
      - cp .env.example .env
      - php artisan key:generate
      - php artisan migrate --force
      - php artisan db:seed --force
      - php artisan cache:clear
      - php artisan config:cache
      - php artisan route:cache
      - php artisan view:cache